name: Publish
on:
  push:
    tags:
      - v*.*.* # run on version tags, e.g. v2.0.0

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Parse Version
        id: get_version
        run: |
          $version=($env:GITHUB_REF -Split '/')[-1]
          Write-Output "::set-output name=version::$version"
    
      - name: Send to pkg.go.dev
        run: |
            ./tools.ps1 publish ${{ steps.get_version.outputs.version }}
